/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
// Auto-generated by build_cutedsl.py -- do not edit
#include "nvfp4_moe_sm110_fc1_relu2_n128.h"
#include "nvfp4_moe_sm110_fc1_relu2_n256.h"
#include "nvfp4_moe_sm110_fc1_swiglu_n128.h"
#include "nvfp4_moe_sm110_fc1_swiglu_n256.h"
#include "nvfp4_moe_sm110_fc2_n128_fp16.h"
#include "nvfp4_moe_sm110_fc2_n256_fp16.h"
