/*
 * SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once
// Auto-generated by build_cutedsl.py -- do not edit
#include "fmha_d128.h"
#include "fmha_d128_fp8.h"
#include "fmha_d128_sw.h"
#include "fmha_d128_sw_fp8.h"
#include "fmha_d64.h"
#include "fmha_d64_fp8.h"
#include "fmha_d64_sw.h"
#include "fmha_d64_sw_fp8.h"
#include "vit_fmha_d128.h"
#include "vit_fmha_d64.h"
#include "vit_fmha_d72.h"
#include "vit_fmha_d80.h"
